server:
  port: 8089

spring:
  application:
    name: search-service

  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:shopsphere}
    password: ${RABBITMQ_PASSWORD:shopsphere123}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  rabbitmq:
    exchange: shopsphere.events
    queue:
      search: search.queue
    routing-key:
      product-all: product.*
